<?php
/**
 * AKS Training module template
 *
 * @category    AKS
 * @package     AKS_Training
 * @author      Alexandr Krivonos <krausweb291985@gmail.com>
 * @copyright   3/22/2016 AKS
 *
 * @var         $this AKS_Training_Block_Customer_Info
 */
?>


<div class="block block-list block-compare">
    <p><<< AKSLEFT >>></p>
    <!-- app/code/local/AKS/Training/Block/Customer/Info.php::getName() -->
    <p><?=$this->getName()?></p>
    <p><?=$this->getTrainingData()?></p>
</div>
